### ISSUE TITLE
How to change background color of menu items displayed also change menu size to wrap content ?

### ISSUE THREAD

**Issue by rahulmanek** [andremion/Floating-Navigation-View#15]

**Comment by andremion** [comment]
Hi @rahulmanek ,
You can try using `android:maxWidth` attribute to decrease a bit the width size.
Regarding item color, it will be possible in the next release.

**Comment by andremion** [comment]
https://github.com/andremion/Floating-Navigation-View/releases/tag/v1.3.0
@rahulmanek ☝🏻
