### ISSUE TITLE
toggle/Switch not working 

### ISSUE THREAD

**Issue by rishabhnayak** [andremion/Floating-Navigation-View#21]

**Comment by Micoder-dev** [comment]
> _No description provided._

Check this commit message i have tested, it's working fine.
If you don't see a toogle switch may be you have to change 
this 
android:actionLayout="@layout/layout_switch"
to this
app:actionLayout="@layout/layout_switch"

https://github.com/Micoder-dev/Self-Studys/commit/d03d303e7b4be84507700912f3c9ef57d62b3805
