### ISSUE TITLE
Themes/colors

### ISSUE THREAD

**Issue by GGLabCenter** [andremion/Floating-Navigation-View#9]
Hello, thanks for the nice lib. I had the accent color as default color for the lib. I want to have a fab with a different background and icon tint, no problems there. But when I open the navigationview I am not able to set properly the colors inside it (I forced the background color programmatically and it works, but if the color is light I need a dark color for the text, and I don't know how to achieve that). Thanks in advance

**Comment by nikitoSha** [comment]
And how to change white color of text and menu icon?

**Comment by andremion** [comment]
Hi @nikitoSha ,
That will be possible in the next release.

**Comment by andremion** [comment]
https://github.com/andremion/Floating-Navigation-View/releases/tag/v1.3.0
@nikitoSha ☝🏻

**Comment by LunevNF** [comment]
> https://github.com/andremion/Floating-Navigation-View/releases/tag/v1.3.0
> @nikitoSha ☝🏻

Best, thanks
